openapi: 3.0.3
info:
  title: Order Creation
  description: |-
    API description for the order creation process in the Digital trade service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
# servers:
  # - url: https://petstore3.swagger.io/api/v3
tags:
  - name: "Buyer - seller"
    description: "Routes in the buyer - seller interface"

  - name: "Seller - buyer"
    description: "Routes in the seller-buyer interface"

components:
  schemas:
    rejectOrderSellerToBuyer:
      type: object
      properties:
        rejectedStatus:
          type: boolean
          description: rejected status of buyer's order
        orderRejectionReason:
          type: string
          description: reason for rejection

    orderResponseBuyerToSeller:
      type: object
      properties:
        orderId:
          type: string
          description: "Buyer's order id"
        orderType:
          type: string
          enum: ["create", "cancel", "update"]
          default: "create"
          description: "Type of order: create/ cancel/ update"
        customerEmailId:
          type: string
          description: "Buyer's personal id"
        date:
          type: object
          description: "Date of creation/ cancellation/rejection/ update"
        allowanceInstructions:
          type: string
          description: "Allowance/charge instructions(freight, documentation)"
        totalCost:
          type: number
          description: "Total cost of buyer's order"
        orders:
          type: array
          description: "List of buyer's orders"
          items:
            properties:
              productName:
                type: string
              productCost:
                type: number
              quantity:
                type: number
        deliveryAddress:
          type: string
          description: "Buyer's address"
        deliveryMethod:
          type: string
          description: "Buyer's preferred delivery method"
        discountOfferId:
          type: string
          description: "Discount offer used by buyer"
        orderConfirmation:
          type: boolean
          description: "Buyer's confirmation of order"
          default: true

    changeOrderBuyerToSeller:
      type: object
      properties:
        orderId:
            type: string
            description: "Buyer's order id"
        orders:
            type: array
            description: "List of the buyer's updated orders"
            items:
              properties:
                productName:
                  type: string
                productCost:
                  type: string
                quantity:
                  type: number
  
    cancelOrderBuyerToSeller:
      type: object
      properties:
        orderId:
            type: string
            description: "Buyer's order id"
        cancellationStatus:
          type: boolean
          description: cancellation signal of buyer's order
        orderCancellationReason:
          type: string
          description: reason for cancellation
          
    registerOrderSellerToBuyer:
      type: object
      properties:
        orderId:
          type: string
          description: "Buyer's order id"
        registered:
          type: boolean
          description: Confirmation of order registration
          default: true
          
    addDetailsSellerToBuyer:
      type: object
      properties:
        details:
          type: string
          description: " Addional details about buyer's order added by seller"
    addDetailsBodySellerToBuyer:
      type: object
      properties:
        orderId:
          type: string
        productId:
          type: string
        quantity:
          type: number
    
    orderReceivalSellerToBuyer:
      type: object
      properties:
        orderStatus:
          type: string
          example: received
    
    orderAcceptanceSellerToBuyer:
      type: object
      properties:
        orderStatus:
          type: string
          example: accepted

  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
paths:
  /seller/rejectOrder/:
    post:
      tags:
        - "Seller - buyer"
      summary: Seller rejects buyer's order.
      description: Send a notifaication to the buyer about the order's rejected status.
      operationId: rejectOrder
      responses:
        '201':
          description: Created response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rejectOrderSellerToBuyer'
        '400':
          description: Bad request

      parameters:
        - name: reason
          in: query
          description: "Reason for rejection"
          required: true
          schema:
            type: string
        - name: orderId
          in: header
          description: "Order id used to reference buyer's order"
          required: true
          schema:
            type: string
        
  /buyer/fetchOrderDetails/:
    get:
      tags:
        - "Buyer - seller"
      summary: Display buyer's order details.
      description: Display buyer's order details.
      operationId: orderResponse
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/orderResponseBuyerToSeller'
        '503':
          description: Service unavailable
      parameters:
        - name: orderId
          required: true
          in: header
          description: "Buyer's order id"
          schema:
            type: "string"
        - name: customerEmailId
          required: true
          in: header
          description: "Buyer's customer id"
          schema:
            type: "string"
        - name: discountOfferId
          required: false
          in: query
          description: "Disount offer id being used by buyer"
          schema:
            type: "string"

  /buyer/changeOrder/{orderId}:
    put:
      tags:
        - "Buyer - seller"
      summary: Change buyer's order.
      description: Change buyer's order.
      operationId: changeOrder
    
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/changeOrderBuyerToSeller'
        '400':
          description: Bad request

      parameters:
        - name: orderId
          required: true
          in: path
          description: "Buyer's order id"
          schema:
            type: "string"
        - name: orders
          in: query
          description: "list of changed orders"
          required: true
          schema:
            type: array
            items:
              type: object
              properties:
                productName:
                  type: string
                productCost:
                  type: string
                quantity:
                  type: number


  /buyer/cancelOrder/{orderId}:
    delete:
      tags:
        - "Buyer - seller"
      summary: Cancel buyer's order.
      description: Cancel buyer's order.
      operationId: cancelOrder

      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cancelOrderBuyerToSeller'
        '400':
          description: Bad request
          # invalid orderId

      # {"orderId": string, "date": string, "reason": string}
      parameters:
        - name: orderId
          required: true
          in: path
          description: "Buyer's order id"
          schema:
            type: string
        - name: reason
          in: query
          description: "Reason for cancellation"
          required: true
          schema:
            type: string
            
  /seller/registerOrder:
    post:
      tags:
        - "Seller - buyer"
      summary: Seller regsiters buyer's order.
      description: Seller should register a buyer's order in the system.
      operationId: registerOrder
      responses:
        '201':
          description: Created response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/registerOrderSellerToBuyer'
        '400':
          description: Bad request

      parameters:
        - name: orderId
          in: query
          description: "Buyer's order id"
          required: true
          schema:
            type: string
            
  /seller/addDetails:
    put:
      tags:
        - "Seller - buyer"
      summary: Seller adds details about buyer's order.
      description: Seller adds additional details about a buyer's order.
      operationId: addDetails
      responses:
        '201':
          description: Created response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addDetailsSellerToBuyer'
        '400':
          description: Bad request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addDetailsBodySellerToBuyer'
      parameters:
        - name: orderId
          in: query
          description: "Buyer's order id"
          required: true
          schema:
            type: string
  
  /seller/orderReceival:
    put:
      tags:
        - Seller - buyer
      summary: Seller recevies the order.
      description: The status of the order turns into received.
      operationId: orderReceival
      responses:
        '200':
          description: Order status changed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/orderReceivalSellerToBuyer'
        '400':
          description: Bad request
      parameters:
        - name: orderId
          in: query
          description: Buyer's order id
          required: true
          schema:
            type: string
  
  /seller/orderAcceptance:
    put:
      tags:
        - "Seller - buyer"
      summary: Seller accepts the order. 
      description: The status of the order turns into accepted.
      operationId: orderAcceptance 
      responses:
        '200':
          description: Order status changed   
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/orderAcceptanceSellerToBuyer'
        '400':
          description: Bad request 